import type { User, InventoryItem, Promotion, MenuCategory } from './types';

export const USERS_DATA: User[] = [
  { id: 1, name: 'Admin User', email: 'admin@example.com', password: 'admin', role: 'admin' },
  { id: 2, name: 'Customer User', email: 'customer@example.com', password: 'customer', role: 'customer' },
];

export const MENU_DATA: MenuCategory[] = [
  {
    name: 'Most Popular',
    items: [
      { name: 'Blue Lagoon', price: 60, image: 'https://placehold.co/600x400/3498db/FFFFFF/png?text=Blue+Lagoon', description: 'A refreshing and vibrant blue mocktail, reminiscent of a tropical paradise. A perfect blend of citrus and sweetness.' },
      { name: 'Red Lagoon', price: 60, image: 'https://placehold.co/600x400/e74c3c/FFFFFF/png?text=Red+Lagoon', description: 'An exotic and tangy red mocktail that tantalizes your taste buds with its fruity punch.' },
      { name: 'Virgin Mojito', price: 60, image: 'https://placehold.co/600x400/2ecc71/FFFFFF/png?text=Virgin+Mojito', description: 'The classic combination of mint and lime, a sparkling and invigorating mocktail for any occasion.' },
      { name: 'Lime Time', price: 50, image: 'https://placehold.co/600x400/f1c40f/FFFFFF/png?text=Lime+Time', description: 'A zesty and sharp lime-flavored drink that is both simple and deeply satisfying.' },
      { name: 'Green Mint', price: 50, image: 'https://placehold.co/600x400/1abc9c/FFFFFF/png?text=Green+Mint', description: 'A cool and crisp mocktail with a powerful fresh mint flavor, perfect for cooling down.' },
      { name: 'Kala Khatta', price: 60, image: 'https://placehold.co/600x400/9b59b6/FFFFFF/png?text=Kala+Khatta', description: 'A traditional Indian tangy and sweet flavor, this mocktail is a nostalgic trip with a modern twist.' },
      { name: 'Green Apple', price: 80, image: 'https://placehold.co/600x400/a2c11c/FFFFFF/png?text=Green+Apple', description: 'Tart and sweet green apple goodness in a glass. A crisp and delightful mocktail.' },
      { name: 'Jeera Masala', price: 50, image: 'https://placehold.co/600x400/7f8c8d/FFFFFF/png?text=Jeera+Masala', description: 'A savory and spicy mocktail featuring roasted cumin. A unique and flavorful digestive drink.' },
      { name: 'Dragon Mojito', price: 110, image: 'https://placehold.co/600x400/d35400/FFFFFF/png?text=Dragon+Mojito', description: 'An exotic mojito with the goodness of dragon fruit, offering a unique taste and a stunning look.' },
    ],
  },
  {
    name: 'Newly Launched',
    items: [
      { name: 'Pink Guava', price: 80, image: 'https://placehold.co/600x400/ff7979/FFFFFF/png?text=Pink+Guava', description: 'Sweet and aromatic, this pink guava mocktail is a tropical delight that transports you to a beach.' },
      { name: 'Red Wine', price: 80, image: 'https://placehold.co/600x400/c0392b/FFFFFF/png?text=Red+Wine', description: 'A sophisticated non-alcoholic red wine mocktail, perfect for celebrations and special evenings.' },
      { name: 'Berry Blast', price: 80, image: 'https://placehold.co/600x400/8e44ad/FFFFFF/png?text=Berry+Blast', description: 'A fantastic explosion of mixed berries, this mocktail is both healthy and delicious.' },
      { name: 'Exotic Berry', price: 70, image: 'https://placehold.co/600x400/2980b9/FFFFFF/png?text=Exotic+Berry', description: 'A blend of rare and exotic berries for a unique flavor profile that is both sweet and tart.' },
      { name: 'Ice Tea', price: 60, image: 'https://placehold.co/600x400/f39c12/FFFFFF/png?text=Ice+Tea', description: 'Classic, refreshing, and subtly sweet. Our ice tea is the perfect thirst quencher.' },
      { name: 'Pina Colada', price: 60, image: 'https://placehold.co/600x400/ecf0f1/34495e/png?text=Pina+Colada', description: 'A creamy and dreamy mocktail with the tropical flavors of pineapple and coconut.' },
    ],
  },
  {
    name: 'Sweet & Soft',
    items: [
      { name: 'Bubblegum', price: 50, image: 'https://placehold.co/600x400/fd79a8/FFFFFF/png?text=Bubblegum', description: 'A fun and sweet mocktail that tastes just like your favorite childhood bubblegum.' },
      { name: 'Cotton Candy', price: 50, image: 'https://placehold.co/600x400/a29bfe/FFFFFF/png?text=Cotton+Candy', description: 'Experience the magical sweetness of cotton candy in this delightful and whimsical drink.' },
      { name: 'Peach', price: 50, image: 'https://placehold.co/600x400/fab1a0/FFFFFF/png?text=Peach', description: 'The delicate and sweet flavor of ripe peaches makes this mocktail a soft and soothing choice.' },
      { name: 'Watermelon', price: 60, image: 'https://placehold.co/600x400/ff6b6b/FFFFFF/png?text=Watermelon', description: 'Juicy and refreshing, this mocktail captures the essence of a fresh slice of watermelon.' },
      { name: 'Black Rose', price: 50, image: 'https://placehold.co/600x400/2d3436/FFFFFF/png?text=Black+Rose', description: 'A mysterious and aromatic mocktail with the subtle, floral notes of black rose.' },
      { name: 'Red Rose', price: 50, image: 'https://placehold.co/600x400/d63031/FFFFFF/png?text=Red+Rose', description: 'A fragrant and romantic mocktail infused with the classic essence of red roses.' },
      { name: 'Strawberry', price: 50, image: 'https://placehold.co/600x400/e84393/FFFFFF/png?text=Strawberry', description: 'Sweet, fruity, and always a favorite. Enjoy the taste of fresh strawberries in this lovely drink.' },
      { name: 'Orange', price: 50, image: 'https://placehold.co/600x400/e67e22/FFFFFF/png?text=Orange', description: 'Bright, citrusy, and full of sunshine. A classic orange mocktail to brighten your day.' },
      { name: 'Kachi Kairi', price: 50, image: 'https://placehold.co/600x400/badc58/FFFFFF/png?text=Kachi+Kairi', description: 'The tangy and sour taste of raw mango in a refreshing mocktail. A true taste of Indian summer.' },
    ],
  },
  {
    name: 'Fruit Punches',
    items: [
      { name: 'Kiwi Crush', price: 80, image: 'https://placehold.co/600x400/9AECDB/FFFFFF/png?text=Kiwi+Crush', description: 'A vibrant and tangy punch made from fresh kiwis. A perfect balance of sweet and sour.' },
      { name: 'Lychee', price: 80, image: 'https://placehold.co/600x400/F97F51/FFFFFF/png?text=Lychee', description: 'Sweet and fragrant lychee punch that is both exotic and incredibly refreshing.' },
      { name: 'Pineapple', price: 80, image: 'https://placehold.co/600x400/F8EFBA/3d3d3d/png?text=Pineapple', description: 'The tropical and tangy taste of pineapple in a cool and refreshing fruit punch.' },
      { name: 'Pan Shot', price: 70, image: 'https://placehold.co/600x400/55E6C1/FFFFFF/png?text=Pan+Shot', description: 'A unique and aromatic drink with the traditional Indian flavor of paan (betel leaf).' },
      { name: 'Black Current', price: 70, image: 'https://placehold.co/600x400/574b90/FFFFFF/png?text=Black+Current', description: 'Rich and flavorful, this black currant punch is a sweet treat for any time of the day.' },
    ],
  },
  {
    name: 'Juices',
    items: [
      { name: 'Mango Juice', price: 50, image: 'https://placehold.co/600x400/f39c12/FFFFFF/png?text=Mango+Juice', description: 'The king of fruits in a glass. Sweet, rich, and pulpy mango juice.' },
      { name: 'Chikoo Juice', price: 40, image: 'https://placehold.co/600x400/b38b6d/FFFFFF/png?text=Chikoo+Juice', description: 'A creamy and naturally sweet juice made from fresh sapodilla.' },
      { name: 'Apple Juice', price: 50, image: 'https://placehold.co/600x400/c0392b/FFFFFF/png?text=Apple+Juice', description: 'Crisp, sweet, and wholesome juice made from the finest apples.' },
      { name: 'Watermelon Juice', price: 40, image: 'https://placehold.co/600x400/ff4757/FFFFFF/png?text=Watermelon+Juice', description: 'The ultimate thirst quencher. Pure, fresh, and hydrating watermelon juice.' },
      { name: 'Orange Juice', price: 50, image: 'https://placehold.co/600x400/e67e22/FFFFFF/png?text=Orange+Juice', description: 'A glass of sunshine. Freshly squeezed orange juice packed with Vitamin C.' },
      { name: 'Carrate Juice', price: 50, image: 'https://placehold.co/600x400/e84118/FFFFFF/png?text=Carrot+Juice', description: 'Healthy and sweet, our carrot juice is a nutritious and tasty choice.' },
      { name: 'Rose Juice', price: 40, image: 'https://placehold.co/600x400/ff5e57/FFFFFF/png?text=Rose+Juice', description: 'A fragrant and soothing juice with the delicate flavor of rose petals.' },
      { name: 'Fruit Salad', price: 40, image: 'https://placehold.co/600x400/32ff7e/FFFFFF/png?text=Fruit+Salad', description: 'A mix of various fresh fruit juices, a healthy and delicious medley.' },
      { name: 'Pineapple Juice', price: 40, image: 'https://placehold.co/600x400/ffc312/FFFFFF/png?text=Pineapple+Juice', description: 'Tangy and tropical, this pineapple juice is a burst of fresh flavor.' },
      { name: 'Strawberry Juice', price: 50, image: 'https://placehold.co/600x400/e84393/FFFFFF/png?text=Strawberry+Juice', description: 'Sweet and delicious juice made from fresh, ripe strawberries.' },
      { name: 'Ganga Jamuna Juice', price: 50, image: 'https://placehold.co/600x400/ff9f1a/FFFFFF/png?text=Ganga+Jamuna', description: 'A classic Indian blend of orange and sweet lime juice, perfectly balanced.' },
      { name: 'Pomegranate Juice', price: 50, image: 'https://placehold.co/600x400/ff3838/FFFFFF/png?text=Pomegranate', description: 'A rich and healthy juice packed with antioxidants and a unique sweet-tart flavor.' },
      { name: 'Mosmbi Juice', price: 50, image: 'https://placehold.co/600x400/d2dae2/3d3d3d/png?text=Mosambi+Juice', description: 'Sweet lime juice, a refreshing and popular choice across India.' },
      { name: 'Maramari Juice', price: 50, image: 'https://placehold.co/600x400/ff9f43/FFFFFF/png?text=Maramari+Juice', description: 'A zesty and flavorful juice blend, perfect for a tangy kick.' },
    ],
  },
  {
    name: 'Shakes',
    items: [
      { name: 'Chocolate Rocks', price: 80, image: 'https://placehold.co/600x400/4b3832/FFFFFF/png?text=Chocolate+Rocks', description: 'A thick and creamy chocolate shake loaded with chocolate chunks.' },
      { name: 'Kit Kat Chunky', price: 90, image: 'https://placehold.co/600x400/c70039/FFFFFF/png?text=Kit+Kat+Chunky', description: 'Have a break with this delicious shake blended with chunky Kit Kat bars.' },
      { name: '5 Star Folks', price: 90, image: 'https://placehold.co/600x400/f39c12/FFFFFF/png?text=5+Star+Folks', description: 'A caramel and nougat-filled chocolate shake inspired by the classic 5 Star bar.' },
      { name: 'Cadbury Dairymilk', price: 90, image: 'https://placehold.co/600x400/5f27cd/FFFFFF/png?text=Dairymilk', description: 'The classic taste of Cadbury Dairymilk in a smooth and creamy shake.' },
      { name: 'Cold Coffee', price: 90, image: 'https://placehold.co/600x400/96624E/FFFFFF/png?text=Cold+Coffee', description: 'A rich and refreshing cold coffee shake, perfectly blended for a caffeine kick.' },
      { name: 'Born Born', price: 90, image: 'https://placehold.co/600x400/8d6e63/FFFFFF/png?text=Bourbon', description: 'A delightful shake made with chocolate bourbon biscuits for a crunchy, chocolaty experience.' },
      { name: 'Oreo Cookies', price: 100, image: 'https://placehold.co/600x400/1e272e/FFFFFF/png?text=Oreo+Cookies', description: 'The world\'s favorite cookie blended into a thick and creamy shake.' },
      { name: 'Choco Pie', price: 100, image: 'https://placehold.co/600x400/532e1c/FFFFFF/png?text=Choco+Pie', description: 'A unique shake that captures the marshmallow and chocolate goodness of a Choco Pie.' },
      { name: 'Cadbury Fruit \'N\' Nutts', price: 100, image: 'https://placehold.co/600x400/6D214F/FFFFFF/png?text=Fruit+N+Nut', description: 'A rich Cadbury shake filled with the goodness of fruits and nuts.' },
      { name: 'Cadbury Silk', price: 100, image: 'https://placehold.co/600x400/4834d4/FFFFFF/png?text=Cadbury+Silk', description: 'Indulge in the silky smooth experience of Cadbury Silk in this premium shake.' },
    ],
  },
  {
    name: 'Chicken Momos (Non-Veg)',
    items: [
        { name: 'Simple Chicken (Steam - Half)', price: 60, image: 'https://placehold.co/600x400/f6e58d/3d3d3d/png?text=Chicken+Momos', description: 'Classic steamed chicken momos, juicy and flavorful. (Half plate)' },
        { name: 'Simple Chicken (Steam - Full)', price: 120, image: 'https://placehold.co/600x400/f6e58d/3d3d3d/png?text=Chicken+Momos', description: 'Classic steamed chicken momos, juicy and flavorful. (Full plate)' },
        { name: 'Simple Chicken (Fried - Half)', price: 70, image: 'https://placehold.co/600x400/f9ca24/3d3d3d/png?text=Fried+Momos', description: 'Crispy fried chicken momos, a delicious and savory snack. (Half plate)' },
        { name: 'Simple Chicken (Fried - Full)', price: 130, image: 'https://placehold.co/600x400/f9ca24/3d3d3d/png?text=Fried+Momos', description: 'Crispy fried chicken momos, a delicious and savory snack. (Full plate)' },
        { name: 'Schezwan Chicken (Steam - Half)', price: 60, image: 'https://placehold.co/600x400/eb4d4b/FFFFFF/png?text=Schezwan+Momos', description: 'Spicy schezwan chicken momos, steamed to perfection. (Half plate)' },
        { name: 'Schezwan Chicken (Steam - Full)', price: 120, image: 'https://placehold.co/600x400/eb4d4b/FFFFFF/png?text=Schezwan+Momos', description: 'Spicy schezwan chicken momos, steamed to perfection. (Full plate)' },
        { name: 'Schezwan Chicken (Fried - Half)', price: 70, image: 'https://placehold.co/600x400/e84118/FFFFFF/png?text=Fried+Schezwan', description: 'Crispy fried momos tossed in a fiery schezwan sauce. (Half plate)' },
        { name: 'Schezwan Chicken (Fried - Full)', price: 130, image: 'https://placehold.co/600x400/e84118/FFFFFF/png?text=Fried+Schezwan', description: 'Crispy fried momos tossed in a fiery schezwan sauce. (Full plate)' },
        { name: 'Cheese Chicken (Steam - Half)', price: 70, image: 'https://placehold.co/600x400/fad390/3d3d3d/png?text=Cheese+Momos', description: 'Juicy chicken momos with a cheesy surprise inside. (Half plate)' },
        { name: 'Cheese Chicken (Steam - Full)', price: 130, image: 'https://placehold.co/600x400/fad390/3d3d3d/png?text=Cheese+Momos', description: 'Juicy chicken momos with a cheesy surprise inside. (Full plate)' },
        { name: 'Cheese Chicken (Fried - Half)', price: 80, image: 'https://placehold.co/600x400/f6b93b/3d3d3d/png?text=Fried+Cheese', description: 'Crispy fried chicken and cheese momos, a perfect indulgence. (Half plate)' },
        { name: 'Cheese Chicken (Fried - Full)', price: 140, image: 'https://placehold.co/600x400/f6b93b/3d3d3d/png?text=Fried+Cheese', description: 'Crispy fried chicken and cheese momos, a perfect indulgence. (Full plate)' },
        { name: 'Achari Chicken (Steam - Half)', price: 70, image: 'https://placehold.co/600x400/cd6133/FFFFFF/png?text=Achari+Momos', description: 'Tangy and flavorful chicken momos with a pickle spice twist. (Half plate)' },
        { name: 'Achari Chicken (Steam - Full)', price: 130, image: 'https://placehold.co/600x400/cd6133/FFFFFF/png?text=Achari+Momos', description: 'Tangy and flavorful chicken momos with a pickle spice twist. (Full plate)' },
        { name: 'Achari Chicken (Fried - Half)', price: 80, image: 'https://placehold.co/600x400/c44569/FFFFFF/png?text=Fried+Achari', description: 'Crispy fried momos with a tangy achari chicken filling. (Half plate)' },
        { name: 'Achari Chicken (Fried - Full)', price: 140, image: 'https://placehold.co/600x400/c44569/FFFFFF/png?text=Fried+Achari', description: 'Crispy fried momos with a tangy achari chicken filling. (Full plate)' },
        { name: 'Chi. Cheese Chicken (Steam - Half)', price: 80, image: 'https://placehold.co/600x400/ff7f50/FFFFFF/png?text=Chilli+Cheese', description: 'Spicy chilli chicken and cheese momos, a flavor explosion. (Half plate)' },
        { name: 'Chi. Cheese Chicken (Steam - Full)', price: 140, image: 'https://placehold.co/600x400/ff7f50/FFFFFF/png?text=Chilli+Cheese', description: 'Spicy chilli chicken and cheese momos, a flavor explosion. (Full plate)' },
        { name: 'Chi. Cheese Chicken (Fried - Half)', price: 90, image: 'https://placehold.co/600x400/ff6348/FFFFFF/png?text=Fried+Chilli+Cheese', description: 'Fried to perfection, with a spicy chilli chicken and cheese filling. (Half plate)' },
        { name: 'Chi. Cheese Chicken (Fried - Full)', price: 150, image: 'https://placehold.co/600x400/ff6348/FFFFFF/png?text=Fried+Chilli+Cheese', description: 'Fried to perfection, with a spicy chilli chicken and cheese filling. (Full plate)' },
        { name: 'Chicken Peri-Peri (Steam - Half)', price: 70, image: 'https://placehold.co/600x400/ff4757/FFFFFF/png?text=Peri-Peri+Momos', description: 'Spicy and tangy peri-peri chicken momos, steamed. (Half plate)' },
        { name: 'Chicken Peri-Peri (Steam - Full)', price: 130, image: 'https://placehold.co/600x400/ff4757/FFFFFF/png?text=Peri-Peri+Momos', description: 'Spicy and tangy peri-peri chicken momos, steamed. (Full plate)' },
        { name: 'Chicken Peri-Peri (Fried - Half)', price: 80, image: 'https://placehold.co/600x400/e056fd/FFFFFF/png?text=Fried+Peri-Peri', description: 'Crispy fried momos with a fiery peri-peri chicken filling. (Half plate)' },
        { name: 'Chicken Peri-Peri (Fried - Full)', price: 140, image: 'https://placehold.co/600x400/e056fd/FFFFFF/png?text=Fried+Peri-Peri', description: 'Crispy fried momos with a fiery peri-peri chicken filling. (Full plate)' },
        { name: 'Chi. Peri-Peri Cheese (Steam - Half)', price: 80, image: 'https://placehold.co/600x400/ff6b81/FFFFFF/png?text=Peri-Peri+Cheese', description: 'A spicy and cheesy delight with peri-peri chicken. (Half plate)' },
        { name: 'Chi. Peri-Peri Cheese (Steam - Full)', price: 140, image: 'https://placehold.co/600x400/ff6b81/FFFFFF/png?text=Peri-Peri+Cheese', description: 'A spicy and cheesy delight with peri-peri chicken. (Full plate)' },
        { name: 'Chi. Peri-Peri Cheese (Fried - Half)', price: 90, image: 'https://placehold.co/600x400/ff9ff3/FFFFFF/png?text=Fried+Peri-Peri+Cheese', description: 'The ultimate momo: fried, spicy, and cheesy. (Half plate)' },
        { name: 'Chi. Peri-Peri Cheese (Fried - Full)', price: 150, image: 'https://placehold.co/600x400/ff9ff3/FFFFFF/png?text=Fried+Peri-Peri+Cheese', description: 'The ultimate momo: fried, spicy, and cheesy. (Full plate)' },
        { name: 'Chicken Kur-Kure (Fried - Half)', price: 90, image: 'https://placehold.co/600x400/feca57/3d3d3d/png?text=Kur-Kure+Momos', description: 'Super crunchy momos with a crispy coating and juicy chicken inside. (Half plate)' },
        { name: 'Chicken Kur-Kure (Fried - Full)', price: 150, image: 'https://placehold.co/600x400/feca57/3d3d3d/png?text=Kur-Kure+Momos', description: 'Super crunchy momos with a crispy coating and juicy chicken inside. (Full plate)' },
        { name: 'Chicken Platter (Steam - Half)', price: 80, image: 'https://placehold.co/600x400/ffc048/3d3d3d/png?text=Chicken+Platter', description: 'An assortment of our best steamed chicken momos. (Half plate)' },
        { name: 'Chicken Platter (Steam - Full)', price: 140, image: 'https://placehold.co/600x400/ffc048/3d3d3d/png?text=Chicken+Platter', description: 'An assortment of our best steamed chicken momos. (Full plate)' },
        { name: 'Chicken Platter (Fried - Half)', price: 90, image: 'https://placehold.co/600x400/ffa801/3d3d3d/png?text=Fried+Chicken+Platter', description: 'An assortment of our best fried chicken momos. (Half plate)' },
        { name: 'Chicken Platter (Fried - Full)', price: 150, image: 'https://placehold.co/600x400/ffa801/3d3d3d/png?text=Fried+Chicken+Platter', description: 'An assortment of our best fried chicken momos. (Full plate)' },
    ],
  },
  {
    name: 'Veg Momos',
    items: [
        { name: 'Simple Veg (Steam - Half)', price: 50, image: 'https://placehold.co/600x400/2ed573/FFFFFF/png?text=Veg+Momos', description: 'Classic steamed vegetable momos, healthy and delicious. (Half plate)' },
        { name: 'Simple Veg (Steam - Full)', price: 100, image: 'https://placehold.co/600x400/2ed573/FFFFFF/png?text=Veg+Momos', description: 'Classic steamed vegetable momos, healthy and delicious. (Full plate)' },
        { name: 'Simple Veg (Fried - Half)', price: 60, image: 'https://placehold.co/600x400/1e90ff/FFFFFF/png?text=Fried+Veg+Momos', description: 'Crispy fried vegetable momos, a perfect snack. (Half plate)' },
        { name: 'Simple Veg (Fried - Full)', price: 110, image: 'https://placehold.co/600x400/1e90ff/FFFFFF/png?text=Fried+Veg+Momos', description: 'Crispy fried vegetable momos, a perfect snack. (Full plate)' },
        { name: 'Schezwan Veg (Steam - Half)', price: 60, image: 'https://placehold.co/600x400/ff6348/FFFFFF/png?text=Schezwan+Veg', description: 'Spicy schezwan vegetable momos, steamed to perfection. (Half plate)' },
        { name: 'Schezwan Veg (Steam - Full)', price: 110, image: 'https://placehold.co/600x400/ff6348/FFFFFF/png?text=Schezwan+Veg', description: 'Spicy schezwan vegetable momos, steamed to perfection. (Full plate)' },
        { name: 'Schezwan Veg (Fried - Half)', price: 60, image: 'https://placehold.co/600x400/ff4757/FFFFFF/png?text=Fried+Schezwan+Veg', description: 'Crispy fried momos tossed in a fiery schezwan sauce. (Half plate)' },
        { name: 'Schezwan Veg (Fried - Full)', price: 110, image: 'https://placehold.co/600x400/ff4757/FFFFFF/png?text=Fried+Schezwan+Veg', description: 'Crispy fried momos tossed in a fiery schezwan sauce. (Full plate)' },
        { name: 'Paneer Achari (Steam - Half)', price: 60, image: 'https://placehold.co/600x400/ff7f50/FFFFFF/png?text=Paneer+Achari', description: 'Tangy and flavorful paneer momos with a pickle spice twist. (Half plate)' },
        { name: 'Paneer Achari (Steam - Full)', price: 110, image: 'https://placehold.co/600x400/ff7f50/FFFFFF/png?text=Paneer+Achari', description: 'Tangy and flavorful paneer momos with a pickle spice twist. (Full plate)' },
        { name: 'Paneer Achari (Fried - Half)', price: 70, image: 'https://placehold.co/600x400/ff6b81/FFFFFF/png?text=Fried+Paneer+Achari', description: 'Crispy fried momos with a tangy achari paneer filling. (Half plate)' },
        { name: 'Paneer Achari (Fried - Full)', price: 120, image: 'https://placehold.co/600x400/ff6b81/FFFFFF/png?text=Fried+Paneer+Achari', description: 'Crispy fried momos with a tangy achari paneer filling. (Full plate)' },
        { name: 'Paneer Cheese (Steam - Half)', price: 80, image: 'https://placehold.co/600x400/ff9ff3/FFFFFF/png?text=Paneer+Cheese', description: 'Creamy paneer and cheese filled momos, a rich delight. (Half plate)' },
        { name: 'Paneer Cheese (Steam - Full)', price: 140, image: 'https://placehold.co/600x400/ff9ff3/FFFFFF/png?text=Paneer+Cheese', description: 'Creamy paneer and cheese filled momos, a rich delight. (Full plate)' },
        { name: 'Paneer Cheese (Fried - Half)', price: 90, image: 'https://placehold.co/600x400/f368e0/FFFFFF/png?text=Fried+Paneer+Cheese', description: 'Fried to golden perfection with a delicious paneer and cheese filling. (Half plate)' },
        { name: 'Paneer Cheese (Fried - Full)', price: 160, image: 'https://placehold.co/600x400/f368e0/FFFFFF/png?text=Fried+Paneer+Cheese', description: 'Fried to golden perfection with a delicious paneer and cheese filling. (Full plate)' },
        { name: 'Simple Paneer (Steam - Half)', price: 60, image: 'https://placehold.co/600x400/feca57/3d3d3d/png?text=Simple+Paneer', description: 'Classic paneer momos, steamed and savory. (Half plate)' },
        { name: 'Simple Paneer (Steam - Full)', price: 110, image: 'https://placehold.co/600x400/feca57/3d3d3d/png?text=Simple+Paneer', description: 'Classic paneer momos, steamed and savory. (Full plate)' },
        { name: 'Simple Paneer (Fried - Half)', price: 70, image: 'https://placehold.co/600x400/ff9f43/3d3d3d/png?text=Fried+Paneer', description: 'Crispy fried momos with a simple and delicious paneer filling. (Half plate)' },
        { name: 'Simple Paneer (Fried - Full)', price: 120, image: 'https://placehold.co/600x400/ff9f43/3d3d3d/png?text=Fried+Paneer', description: 'Crispy fried momos with a simple and delicious paneer filling. (Full plate)' },
        { name: 'Veg Cheese (Steam - Half)', price: 70, image: 'https://placehold.co/600x400/54a0ff/FFFFFF/png?text=Veg+Cheese', description: 'A delightful combination of mixed vegetables and cheese in a steamed momo. (Half plate)' },
        { name: 'Veg Cheese (Steam - Full)', price: 120, image: 'https://placehold.co/600x400/54a0ff/FFFFFF/png?text=Veg+Cheese', description: 'A delightful combination of mixed vegetables and cheese in a steamed momo. (Full plate)' },
        { name: 'Veg Cheese (Fried - Half)', price: 70, image: 'https://placehold.co/600x400/5758BB/FFFFFF/png?text=Fried+Veg+Cheese', description: 'Crispy fried momos with a savory vegetable and cheese filling. (Half plate)' },
        { name: 'Veg Cheese (Fried - Full)', price: 130, image: 'https://placehold.co/600x400/5758BB/FFFFFF/png?text=Fried+Veg+Cheese', description: 'Crispy fried momos with a savory vegetable and cheese filling. (Full plate)' },
        { name: 'Corn Cheese (Steam - Half)', price: 70, image: 'https://placehold.co/600x400/ffd32a/3d3d3d/png?text=Corn+Cheese', description: 'Sweet corn and cheese filled momos, a favorite for all ages. (Half plate)' },
        { name: 'Corn Cheese (Steam - Full)', price: 130, image: 'https://placehold.co/600x400/ffd32a/3d3d3d/png?text=Corn+Cheese', description: 'Sweet corn and cheese filled momos, a favorite for all ages. (Full plate)' },
        { name: 'Corn Cheese (Fried - Half)', price: 70, image: 'https://placehold.co/600x400/ffc048/3d3d3d/png?text=Fried+Corn+Cheese', description: 'Crispy fried momos with a delicious sweet corn and cheese filling. (Half plate)' },
        { name: 'Corn Cheese (Fried - Full)', price: 130, image: 'https://placehold.co/600x400/ffc048/3d3d3d/png?text=Fried+Corn+Cheese', description: 'Crispy fried momos with a delicious sweet corn and cheese filling. (Full plate)' },
        { name: 'Veg Chilli Cheese (Steam - Half)', price: 80, image: 'https://placehold.co/600x400/ff3f34/FFFFFF/png?text=Veg+Chilli+Cheese', description: 'Spicy and cheesy momos with a mixed vegetable filling. (Half plate)' },
        { name: 'Veg Chilli Cheese (Steam - Full)', price: 140, image: 'https://placehold.co/600x400/ff3f34/FFFFFF/png?text=Veg+Chilli+Cheese', description: 'Spicy and cheesy momos with a mixed vegetable filling. (Full plate)' },
        { name: 'Veg Chilli Cheese (Fried - Half)', price: 80, image: 'https://placehold.co/600x400/ea2027/FFFFFF/png?text=Fried+Veg+Chilli+Cheese', description: 'Crispy fried momos with a spicy vegetable and cheese filling. (Half plate)' },
        { name: 'Veg Chilli Cheese (Fried - Full)', price: 140, image: 'https://placehold.co/600x400/ea2027/FFFFFF/png?text=Fried+Veg+Chilli+Cheese', description: 'Crispy fried momos with a spicy vegetable and cheese filling. (Full plate)' },
        { name: 'Veg Kur-Kure (Fried - Half)', price: 80, image: 'https://placehold.co/600x400/ffc048/3d3d3d/png?text=Veg+Kur-Kure', description: 'Super crunchy momos with a crispy coating and vegetable filling. (Half plate)' },
        { name: 'Veg Kur-Kure (Fried - Full)', price: 140, image: 'https://placehold.co/600x400/ffc048/3d3d3d/png?text=Veg+Kur-Kure', description: 'Super crunchy momos with a crispy coating and vegetable filling. (Full plate)' },
        { name: 'Veg Platter (Steam - Half)', price: 70, image: 'https://placehold.co/600x400/009432/FFFFFF/png?text=Veg+Platter', description: 'An assortment of our best steamed vegetable momos. (Half plate)' },
        { name: 'Veg Platter (Steam - Full)', price: 130, image: 'https://placehold.co/600x400/009432/FFFFFF/png?text=Veg+Platter', description: 'An assortment of our best steamed vegetable momos. (Full plate)' },
        { name: 'Veg Platter (Fried - Half)', price: 80, image: 'https://placehold.co/600x400/20bf6b/FFFFFF/png?text=Fried+Veg+Platter', description: 'An assortment of our best fried vegetable momos. (Half plate)' },
        { name: 'Veg Platter (Fried - Full)', price: 140, image: 'https://placehold.co/600x400/20bf6b/FFFFFF/png?text=Fried+Veg+Platter', description: 'An assortment of our best fried vegetable momos. (Full plate)' },
    ],
  },
];

export const INVENTORY_DATA: InventoryItem[] = [
    { id: 1, name: 'Oranges', category: 'Fruits', stock: 50, unit: 'kg', price: 80, threshold: 10 },
    { id: 2, name: 'Apples', category: 'Fruits', stock: 40, unit: 'kg', price: 120, threshold: 10 },
    { id: 3, name: 'Watermelons', category: 'Fruits', stock: 20, unit: 'units', price: 150, threshold: 5 },
    { id: 4, name: 'Mint Leaves', category: 'Herbs', stock: 2, unit: 'kg', price: 200, threshold: 0.5 },
    { id: 5, name: 'Sugar Syrup', category: 'Syrups', stock: 10, unit: 'liters', price: 100, threshold: 2 },
    { id: 6, name: 'Chicken', category: 'Meat', stock: 15, unit: 'kg', price: 250, threshold: 3 },
    { id: 7, name: 'Paneer', category: 'Dairy', stock: 10, unit: 'kg', price: 300, threshold: 2 },
    { id: 8, name: 'Ice', category: 'Misc', stock: 100, unit: 'kg', price: 10, threshold: 20 },
];

export const PROMOTIONS_DATA: Promotion[] = [
  {
    id: 1,
    name: 'Mojito Mania',
    description: 'Get 15% off on our most popular Mojitos.',
    discountType: 'percentage',
    discountValue: 15,
    applicableItems: ['Virgin Mojito', 'Dragon Mojito', 'Lime Time'],
    startDate: '2024-01-01',
    endDate: '2024-12-31',
    isActive: true,
  },
  {
    id: 2,
    name: 'Juicy Deals',
    description: 'Flat ₹10 off on select juices.',
    discountType: 'fixed',
    discountValue: 10,
    applicableItems: ['Mango Juice', 'Apple Juice', 'Orange Juice', 'Watermelon Juice'],
    startDate: '2024-06-01',
    endDate: '2024-08-31',
    isActive: true,
  },
  {
    id: 3,
    name: 'Shake It Up!',
    description: '10% off on all Shakes.',
    discountType: 'percentage',
    discountValue: 10,
    applicableItems: [
        'Chocolate Rocks', 'Kit Kat Chunky', '5 Star Folks', 'Cadbury Dairymilk', 
        'Cold Coffee', 'Born Born', 'Oreo Cookies', 'Choco Pie', 
        'Cadbury Fruit \'N\' Nutts', 'Cadbury Silk'
    ],
    startDate: '2024-01-01',
    endDate: '2024-12-31',
    isActive: false,
  },
];
